[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlayout.ld"]
runner = "qemu-system-riscv64 -s -S -machine virt -cpu rv64 -m 128M -nographic -bios default -kernel"
