[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlayout.ld"]
runner = "qemu-system-riscv64 -s -machine virt -cpu rv64 -m 128M -nographic -bios default -kernel"
